version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.1.0
jobs:
  continue:
    executor: continuation/default
    steps:
      - checkout
      - run: |
          generate-pipeline-config
      - continuation/continue:
          parameters: '{}'
          configuration_path: config.yml
workflows:
  setup-workflow:
    jobs:
      - continue