version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.1.0
jobs:
  generate-config:
    executor: continuation/default
    steps:
      - checkout
      - run: 
          name: Generate Pipeline config.yml file
          command: |
            ./scripts/generate-pipeline-config "0.14.2" "1.59.0" # Terraform CLI and Digital Ocean versions to install
      - continuation/continue:
          parameters: '{}'
          configuration_path: configs/generated_config.yml
workflows:
  setup-workflow:
    jobs:
      - generate-config