version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.1.0
jobs:
  generate-config:
    executor: continuation/default
    steps:
      - checkout
      - run: 
          name: Generate Pipeline config.yml file
          command: |
            ./generate-pipeline-config
      - continuation/continue:
          parameters: '{}'
          configuration_path: config.yml
workflows:
  setup-workflow:
    jobs:
      - generate-config